AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ROLE:
    Type: String
  SNSTOPIC:
    Type: String
Resources:
  happyfaceCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resumeChecker
      Description: Check the jasoniharris website is alive
      Handler: function.handler
      CodeUri: s3://jasoniharris-resume-checker/c8b1f62eea02c0e6c2212950abee02a0
      Runtime: python3.6
      MemorySize: 128
      Timeout: 30
      Role:
        Ref: ROLE
      Environment:
        Variables:
          SNSTOPIC:
            Ref: SNSTOPIC
