AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ROLE:
    Type: String
  SNSTOPIC:
    Type: String

Resources:
  resumeCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resumeChecker
      Description: Check the jasoniharris website is alive
      Handler: function.handler
      CodeUri: ./function.py
      Runtime: python3.6
      MemorySize: 128
      Timeout: 30
      Role: !Ref ROLE
      Environment:
        Variables:
          SNSTOPIC: !Ref SNSTOPIC
  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(6 hours)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "resumeCheckerFunction"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "resumeCheckerFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"
