AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ROLE:
    Type: String
  SNSTOPIC:
    Type: String

Resources:
  happyfaceCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resumeChecker
      Description: Check the jasoniharris website is alive
      Handler: function.handler
      CodeUri: ./function.py
      Runtime: python3.6
      MemorySize: 128
      Timeout: 30
      Role: !Ref ROLE
      Environment:
        Variables:
          SNSTOPIC: !Ref SNSTOPIC
